### ISSUE TITLE
Remove `require-main` rule

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/npm-package-json-lint-config#49]
Currently, we require the `main` field:

https://github.com/stylelint/npm-package-json-lint-config/blob/9e7d6b22ab84a4f24869928a9386ff3a13b2668b/lib/npm-package-json-lint-config.js#L20

However, when writing an ECMAScript module (ESM), `main` is not always necessary. Instead, the `exports` field is required. So, should we remove the `require-main` rule from this config?

See also the [Node.js documentation](https://nodejs.org/api/packages.html#main-entry-point-export).

---

Note: Until pure ESM packages spread, we can just ignore the rule like this:

```diff json
 {
   "extends": "@stylelint/npm-package-json-lint-config",
+  "rules": {
+    "require-main": "off"
+  }
 }
```

**Comment by jeddy3** [comment]
SGTM.
